// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_state.proto

package com.elarian.hera.proto;

public final class AppStateOuterClass {
  private AppStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AppStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.AppState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     * @return The data.
     */
    com.elarian.hera.proto.CommonModel.DataMapValue getData();

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    java.util.List<com.elarian.hera.proto.AppModel.CustomerReminder> 
        getRemindersList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    com.elarian.hera.proto.AppModel.CustomerReminder getReminders(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    int getRemindersCount();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.AppState}
   */
  public  static final class AppState extends
      com.google.protobuf.GeneratedMessageLite<
          AppState, AppState.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.AppState)
      AppStateOrBuilder {
    private AppState() {
      reminders_ = emptyProtobufList();
    }
    public static final int DATA_FIELD_NUMBER = 1;
    private com.elarian.hera.proto.CommonModel.DataMapValue data_;
    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.DataMapValue getData() {
      return data_ == null ? com.elarian.hera.proto.CommonModel.DataMapValue.getDefaultInstance() : data_;
    }
    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     */
    private void setData(com.elarian.hera.proto.CommonModel.DataMapValue value) {
      value.getClass();
  data_ = value;
      
      }
    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeData(com.elarian.hera.proto.CommonModel.DataMapValue value) {
      value.getClass();
  if (data_ != null &&
          data_ != com.elarian.hera.proto.CommonModel.DataMapValue.getDefaultInstance()) {
        data_ =
          com.elarian.hera.proto.CommonModel.DataMapValue.newBuilder(data_).mergeFrom(value).buildPartial();
      } else {
        data_ = value;
      }
      
    }
    /**
     * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
     */
    private void clearData() {  data_ = null;
      
    }

    public static final int REMINDERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.AppModel.CustomerReminder> reminders_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.AppModel.CustomerReminder> getRemindersList() {
      return reminders_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.AppModel.CustomerReminderOrBuilder> 
        getRemindersOrBuilderList() {
      return reminders_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    @java.lang.Override
    public int getRemindersCount() {
      return reminders_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.AppModel.CustomerReminder getReminders(int index) {
      return reminders_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    public com.elarian.hera.proto.AppModel.CustomerReminderOrBuilder getRemindersOrBuilder(
        int index) {
      return reminders_.get(index);
    }
    private void ensureRemindersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.AppModel.CustomerReminder> tmp = reminders_;
      if (!tmp.isModifiable()) {
        reminders_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    private void setReminders(
        int index, com.elarian.hera.proto.AppModel.CustomerReminder value) {
      value.getClass();
  ensureRemindersIsMutable();
      reminders_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    private void addReminders(com.elarian.hera.proto.AppModel.CustomerReminder value) {
      value.getClass();
  ensureRemindersIsMutable();
      reminders_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    private void addReminders(
        int index, com.elarian.hera.proto.AppModel.CustomerReminder value) {
      value.getClass();
  ensureRemindersIsMutable();
      reminders_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    private void addAllReminders(
        java.lang.Iterable<? extends com.elarian.hera.proto.AppModel.CustomerReminder> values) {
      ensureRemindersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, reminders_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    private void clearReminders() {
      reminders_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
     */
    private void removeReminders(int index) {
      ensureRemindersIsMutable();
      reminders_.remove(index);
    }

    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.AppStateOuterClass.AppState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.AppStateOuterClass.AppState prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.AppState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.AppStateOuterClass.AppState, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.AppState)
        com.elarian.hera.proto.AppStateOuterClass.AppStateOrBuilder {
      // Construct using com.elarian.hera.proto.AppStateOuterClass.AppState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.CommonModel.DataMapValue getData() {
        return instance.getData();
      }
      /**
       * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
       */
      public Builder setData(com.elarian.hera.proto.CommonModel.DataMapValue value) {
        copyOnWrite();
        instance.setData(value);
        return this;
        }
      /**
       * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
       */
      public Builder setData(
          com.elarian.hera.proto.CommonModel.DataMapValue.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
       */
      public Builder mergeData(com.elarian.hera.proto.CommonModel.DataMapValue value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.DataMapValue data = 1;</code>
       */
      public Builder clearData() {  copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.AppModel.CustomerReminder> getRemindersList() {
        return java.util.Collections.unmodifiableList(
            instance.getRemindersList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      @java.lang.Override
      public int getRemindersCount() {
        return instance.getRemindersCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.AppModel.CustomerReminder getReminders(int index) {
        return instance.getReminders(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder setReminders(
          int index, com.elarian.hera.proto.AppModel.CustomerReminder value) {
        copyOnWrite();
        instance.setReminders(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder setReminders(
          int index, com.elarian.hera.proto.AppModel.CustomerReminder.Builder builderForValue) {
        copyOnWrite();
        instance.setReminders(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder addReminders(com.elarian.hera.proto.AppModel.CustomerReminder value) {
        copyOnWrite();
        instance.addReminders(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder addReminders(
          int index, com.elarian.hera.proto.AppModel.CustomerReminder value) {
        copyOnWrite();
        instance.addReminders(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder addReminders(
          com.elarian.hera.proto.AppModel.CustomerReminder.Builder builderForValue) {
        copyOnWrite();
        instance.addReminders(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder addReminders(
          int index, com.elarian.hera.proto.AppModel.CustomerReminder.Builder builderForValue) {
        copyOnWrite();
        instance.addReminders(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder addAllReminders(
          java.lang.Iterable<? extends com.elarian.hera.proto.AppModel.CustomerReminder> values) {
        copyOnWrite();
        instance.addAllReminders(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder clearReminders() {
        copyOnWrite();
        instance.clearReminders();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerReminder reminders = 2;</code>
       */
      public Builder removeReminders(int index) {
        copyOnWrite();
        instance.removeReminders(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.AppState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.AppStateOuterClass.AppState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "data_",
              "reminders_",
              com.elarian.hera.proto.AppModel.CustomerReminder.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\t\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.AppStateOuterClass.AppState> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.AppStateOuterClass.AppState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.AppStateOuterClass.AppState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.AppState)
    private static final com.elarian.hera.proto.AppStateOuterClass.AppState DEFAULT_INSTANCE;
    static {
      AppState defaultInstance = new AppState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AppState.class, defaultInstance);
    }

    public static com.elarian.hera.proto.AppStateOuterClass.AppState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AppState> PARSER;

    public static com.google.protobuf.Parser<AppState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
