// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity_state.proto

package com.elarian.hera.proto;

public final class IdentityStateOuterClass {
  private IdentityStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IdentityStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.IdentityState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> 
        getTagsList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerIndex getTags(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    int getTagsCount();

    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    int getMetadataCount();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    getMetadata();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    getMetadataMap();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */

    com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrDefault(
        java.lang.String key,
        com.elarian.hera.proto.CommonModel.DataMapValue defaultValue);
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */

    com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrThrow(
        java.lang.String key);

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> 
        getSecondaryIdsList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerIndex getSecondaryIds(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    int getSecondaryIdsCount();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.IdentityState}
   */
  public  static final class IdentityState extends
      com.google.protobuf.GeneratedMessageLite<
          IdentityState, IdentityState.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.IdentityState)
      IdentityStateOrBuilder {
    private IdentityState() {
      tags_ = emptyProtobufList();
      secondaryIds_ = emptyProtobufList();
    }
    public static final int TAGS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerIndex> tags_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerIndex getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    public com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }
    private void ensureTagsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerIndex> tmp = tags_;
      if (!tmp.isModifiable()) {
        tags_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    private void setTags(
        int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
      value.getClass();
  ensureTagsIsMutable();
      tags_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    private void addTags(com.elarian.hera.proto.CommonModel.CustomerIndex value) {
      value.getClass();
  ensureTagsIsMutable();
      tags_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    private void addTags(
        int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
      value.getClass();
  ensureTagsIsMutable();
      tags_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    private void addAllTags(
        java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerIndex> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, tags_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    private void clearTags() {
      tags_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    private void removeTags(int index) {
      ensureTagsIsMutable();
      tags_.remove(index);
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.elarian.hera.proto.CommonModel.DataMapValue.getDefaultInstance());
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> metadata_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    internalGetMetadata() {
      return metadata_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    internalGetMutableMetadata() {
      if (!metadata_.isMutable()) {
        metadata_ = metadata_.mutableCopy();
      }
      return metadata_;
    }
    @java.lang.Override

    public int getMetadataCount() {
      return internalGetMetadata().size();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public boolean containsMetadata(
        java.lang.String key) {
      key.getClass();
      return internalGetMetadata().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadataMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetMetadata());
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrDefault(
        java.lang.String key,
        com.elarian.hera.proto.CommonModel.DataMapValue defaultValue) {
      key.getClass();
      java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
          internalGetMetadata();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrThrow(
        java.lang.String key) {
      key.getClass();
      java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
          internalGetMetadata();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    private java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    getMutableMetadataMap() {
      return internalGetMutableMetadata();
    }

    public static final int SECONDARY_IDS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerIndex> secondaryIds_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getSecondaryIdsList() {
      return secondaryIds_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
        getSecondaryIdsOrBuilderList() {
      return secondaryIds_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public int getSecondaryIdsCount() {
      return secondaryIds_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerIndex getSecondaryIds(int index) {
      return secondaryIds_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    public com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getSecondaryIdsOrBuilder(
        int index) {
      return secondaryIds_.get(index);
    }
    private void ensureSecondaryIdsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerIndex> tmp = secondaryIds_;
      if (!tmp.isModifiable()) {
        secondaryIds_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    private void setSecondaryIds(
        int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
      value.getClass();
  ensureSecondaryIdsIsMutable();
      secondaryIds_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    private void addSecondaryIds(com.elarian.hera.proto.CommonModel.CustomerIndex value) {
      value.getClass();
  ensureSecondaryIdsIsMutable();
      secondaryIds_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    private void addSecondaryIds(
        int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
      value.getClass();
  ensureSecondaryIdsIsMutable();
      secondaryIds_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    private void addAllSecondaryIds(
        java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerIndex> values) {
      ensureSecondaryIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, secondaryIds_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    private void clearSecondaryIds() {
      secondaryIds_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    private void removeSecondaryIds(int index) {
      ensureSecondaryIdsIsMutable();
      secondaryIds_.remove(index);
    }

    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.IdentityStateOuterClass.IdentityState prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.IdentityState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.IdentityStateOuterClass.IdentityState, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.IdentityState)
        com.elarian.hera.proto.IdentityStateOuterClass.IdentityStateOrBuilder {
      // Construct using com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getTagsList() {
        return java.util.Collections.unmodifiableList(
            instance.getTagsList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      @java.lang.Override
      public int getTagsCount() {
        return instance.getTagsCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.CommonModel.CustomerIndex getTags(int index) {
        return instance.getTags(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder setTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        copyOnWrite();
        instance.setTags(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder setTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        copyOnWrite();
        instance.setTags(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        copyOnWrite();
        instance.addTags(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        copyOnWrite();
        instance.addTags(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(
          com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        copyOnWrite();
        instance.addTags(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        copyOnWrite();
        instance.addTags(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerIndex> values) {
        copyOnWrite();
        instance.addAllTags(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder clearTags() {
        copyOnWrite();
        instance.clearTags();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder removeTags(int index) {
        copyOnWrite();
        instance.removeTags(index);
        return this;
      }

      @java.lang.Override

      public int getMetadataCount() {
        return instance.getMetadataMap().size();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override

      public boolean containsMetadata(
          java.lang.String key) {
        key.getClass();
        return instance.getMetadataMap().containsKey(key);
      }

      public Builder clearMetadata() {
        copyOnWrite();
        instance.getMutableMetadataMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */

      public Builder removeMetadata(
          java.lang.String key) {
        key.getClass();
        copyOnWrite();
        instance.getMutableMetadataMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadataMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getMetadataMap());
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override

      public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrDefault(
          java.lang.String key,
          com.elarian.hera.proto.CommonModel.DataMapValue defaultValue) {
        key.getClass();
        java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
            instance.getMetadataMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override

      public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrThrow(
          java.lang.String key) {
        key.getClass();
        java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
            instance.getMetadataMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          com.elarian.hera.proto.CommonModel.DataMapValue value) {
        key.getClass();
        value.getClass();
        copyOnWrite();
        instance.getMutableMetadataMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      public Builder putAllMetadata(
          java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> values) {
        copyOnWrite();
        instance.getMutableMetadataMap().putAll(values);
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getSecondaryIdsList() {
        return java.util.Collections.unmodifiableList(
            instance.getSecondaryIdsList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      @java.lang.Override
      public int getSecondaryIdsCount() {
        return instance.getSecondaryIdsCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.CommonModel.CustomerIndex getSecondaryIds(int index) {
        return instance.getSecondaryIds(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder setSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        copyOnWrite();
        instance.setSecondaryIds(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder setSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        copyOnWrite();
        instance.setSecondaryIds(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        copyOnWrite();
        instance.addSecondaryIds(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        copyOnWrite();
        instance.addSecondaryIds(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(
          com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        copyOnWrite();
        instance.addSecondaryIds(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        copyOnWrite();
        instance.addSecondaryIds(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addAllSecondaryIds(
          java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerIndex> values) {
        copyOnWrite();
        instance.addAllSecondaryIds(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder clearSecondaryIds() {
        copyOnWrite();
        instance.clearSecondaryIds();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder removeSecondaryIds(int index) {
        copyOnWrite();
        instance.removeSecondaryIds(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.IdentityState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.IdentityStateOuterClass.IdentityState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "tags_",
              com.elarian.hera.proto.CommonModel.CustomerIndex.class,
              "metadata_",
              MetadataDefaultEntryHolder.defaultEntry,
              "secondaryIds_",
              com.elarian.hera.proto.CommonModel.CustomerIndex.class,
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0001\u0002\u0000\u0001\u001b\u00022\u0003" +
                "\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.IdentityStateOuterClass.IdentityState> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.IdentityStateOuterClass.IdentityState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.IdentityState)
    private static final com.elarian.hera.proto.IdentityStateOuterClass.IdentityState DEFAULT_INSTANCE;
    static {
      IdentityState defaultInstance = new IdentityState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IdentityState.class, defaultInstance);
    }

    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IdentityState> PARSER;

    public static com.google.protobuf.Parser<IdentityState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
