// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity_model.proto

package com.elarian.hera.proto;

public final class ActivityModel {
  private ActivityModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.elarian.hera.proto.ActivityChannel}
   */
  public enum ActivityChannel
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>ACTIVITY_CHANNEL_UNSPECIFIED = 0;</code>
     */
    ACTIVITY_CHANNEL_UNSPECIFIED(0),
    /**
     * <code>ACTIVITY_CHANNEL_WEB = 1;</code>
     */
    ACTIVITY_CHANNEL_WEB(1),
    /**
     * <code>ACTIVITY_CHANNEL_MOBILE = 2;</code>
     */
    ACTIVITY_CHANNEL_MOBILE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACTIVITY_CHANNEL_UNSPECIFIED = 0;</code>
     */
    public static final int ACTIVITY_CHANNEL_UNSPECIFIED_VALUE = 0;
    /**
     * <code>ACTIVITY_CHANNEL_WEB = 1;</code>
     */
    public static final int ACTIVITY_CHANNEL_WEB_VALUE = 1;
    /**
     * <code>ACTIVITY_CHANNEL_MOBILE = 2;</code>
     */
    public static final int ACTIVITY_CHANNEL_MOBILE_VALUE = 2;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActivityChannel valueOf(int value) {
      return forNumber(value);
    }

    public static ActivityChannel forNumber(int value) {
      switch (value) {
        case 0: return ACTIVITY_CHANNEL_UNSPECIFIED;
        case 1: return ACTIVITY_CHANNEL_WEB;
        case 2: return ACTIVITY_CHANNEL_MOBILE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ActivityChannel>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ActivityChannel> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ActivityChannel>() {
            @java.lang.Override
            public ActivityChannel findValueByNumber(int number) {
              return ActivityChannel.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return ActivityChannelVerifier.INSTANCE;
    }

    private static final class ActivityChannelVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ActivityChannelVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return ActivityChannel.forNumber(number) != null;
            }
          };

    private final int value;

    private ActivityChannel(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.elarian.hera.proto.ActivityChannel)
  }

  public interface ActivityChannelNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.ActivityChannelNumber)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     * @return The enum numeric value on the wire for channel.
     */
    int getChannelValue();
    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     * @return The channel.
     */
    com.elarian.hera.proto.ActivityModel.ActivityChannel getChannel();

    /**
     * <code>string number = 2;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.ActivityChannelNumber}
   */
  public  static final class ActivityChannelNumber extends
      com.google.protobuf.GeneratedMessageLite<
          ActivityChannelNumber, ActivityChannelNumber.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.ActivityChannelNumber)
      ActivityChannelNumberOrBuilder {
    private ActivityChannelNumber() {
      number_ = "";
    }
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private int channel_;
    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     * @return The enum numeric value on the wire for channel.
     */
    @java.lang.Override
    public int getChannelValue() {
      return channel_;
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     * @return The channel.
     */
    @java.lang.Override
    public com.elarian.hera.proto.ActivityModel.ActivityChannel getChannel() {
      com.elarian.hera.proto.ActivityModel.ActivityChannel result = com.elarian.hera.proto.ActivityModel.ActivityChannel.forNumber(channel_);
      return result == null ? com.elarian.hera.proto.ActivityModel.ActivityChannel.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     * @param value The enum numeric value on the wire for channel to set.
     */
    private void setChannelValue(int value) {
        channel_ = value;
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     * @param value The channel to set.
     */
    private void setChannel(com.elarian.hera.proto.ActivityModel.ActivityChannel value) {
      channel_ = value.getNumber();
      
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
     */
    private void clearChannel() {
      
      channel_ = 0;
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private java.lang.String number_;
    /**
     * <code>string number = 2;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      return number_;
    }
    /**
     * <code>string number = 2;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(number_);
    }
    /**
     * <code>string number = 2;</code>
     * @param value The number to set.
     */
    private void setNumber(
        java.lang.String value) {
      value.getClass();
  
      number_ = value;
    }
    /**
     * <code>string number = 2;</code>
     */
    private void clearNumber() {
      
      number_ = getDefaultInstance().getNumber();
    }
    /**
     * <code>string number = 2;</code>
     * @param value The bytes for number to set.
     */
    private void setNumberBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      number_ = value.toStringUtf8();
      
    }

    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.ActivityModel.ActivityChannelNumber prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.ActivityChannelNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.ActivityModel.ActivityChannelNumber, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.ActivityChannelNumber)
        com.elarian.hera.proto.ActivityModel.ActivityChannelNumberOrBuilder {
      // Construct using com.elarian.hera.proto.ActivityModel.ActivityChannelNumber.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
       * @return The enum numeric value on the wire for channel.
       */
      @java.lang.Override
      public int getChannelValue() {
        return instance.getChannelValue();
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannelValue(int value) {
        copyOnWrite();
        instance.setChannelValue(value);
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
       * @return The channel.
       */
      @java.lang.Override
      public com.elarian.hera.proto.ActivityModel.ActivityChannel getChannel() {
        return instance.getChannel();
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
       * @param value The enum numeric value on the wire for channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(com.elarian.hera.proto.ActivityModel.ActivityChannel value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannel channel = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }

      /**
       * <code>string number = 2;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        return instance.getNumber();
      }
      /**
       * <code>string number = 2;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        return instance.getNumberBytes();
      }
      /**
       * <code>string number = 2;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        copyOnWrite();
        instance.setNumber(value);
        return this;
      }
      /**
       * <code>string number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        copyOnWrite();
        instance.clearNumber();
        return this;
      }
      /**
       * <code>string number = 2;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNumberBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.ActivityChannelNumber)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.ActivityModel.ActivityChannelNumber();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "channel_",
              "number_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.ActivityModel.ActivityChannelNumber> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.ActivityModel.ActivityChannelNumber.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.ActivityModel.ActivityChannelNumber>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.ActivityChannelNumber)
    private static final com.elarian.hera.proto.ActivityModel.ActivityChannelNumber DEFAULT_INSTANCE;
    static {
      ActivityChannelNumber defaultInstance = new ActivityChannelNumber();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ActivityChannelNumber.class, defaultInstance);
    }

    public static com.elarian.hera.proto.ActivityModel.ActivityChannelNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ActivityChannelNumber> PARSER;

    public static com.google.protobuf.Parser<ActivityChannelNumber> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CustomerActivityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.CustomerActivity)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    int getPropertiesCount();
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    boolean containsProperties(
        java.lang.String key);
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getProperties();
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getPropertiesMap();
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */

    java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */

    java.lang.String getPropertiesOrThrow(
        java.lang.String key);

    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.CustomerActivity}
   */
  public  static final class CustomerActivity extends
      com.google.protobuf.GeneratedMessageLite<
          CustomerActivity, CustomerActivity.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.CustomerActivity)
      CustomerActivityOrBuilder {
    private CustomerActivity() {
      key_ = "";
    }
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.String key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return key_;
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(key_);
    }
    /**
     * <code>string key = 1;</code>
     * @param value The key to set.
     */
    private void setKey(
        java.lang.String value) {
      value.getClass();
  
      key_ = value;
    }
    /**
     * <code>string key = 1;</code>
     */
    private void clearKey() {
      
      key_ = getDefaultInstance().getKey();
    }
    /**
     * <code>string key = 1;</code>
     * @param value The bytes for key to set.
     */
    private void setKeyBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      key_ = value.toStringUtf8();
      
    }

    public static final int PROPERTIES_FIELD_NUMBER = 2;
    private static final class PropertiesDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.String> properties_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetProperties() {
      return properties_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
    internalGetMutableProperties() {
      if (!properties_.isMutable()) {
        properties_ = properties_.mutableCopy();
      }
      return properties_;
    }
    @java.lang.Override

    public int getPropertiesCount() {
      return internalGetProperties().size();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    @java.lang.Override

    public boolean containsProperties(
        java.lang.String key) {
      key.getClass();
      return internalGetProperties().containsKey(key);
    }
    /**
     * Use {@link #getPropertiesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getProperties() {
      return getPropertiesMap();
    }
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetProperties());
    }
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getPropertiesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getPropertiesOrThrow(
        java.lang.String key) {
      key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetProperties();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; properties = 2;</code>
     */
    private java.util.Map<java.lang.String, java.lang.String>
    getMutablePropertiesMap() {
      return internalGetMutableProperties();
    }

    public static final int CREATED_AT_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    private void setCreatedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  createdAt_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCreatedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        createdAt_ =
          com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
      } else {
        createdAt_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 3;</code>
     */
    private void clearCreatedAt() {  createdAt_ = null;
      
    }

    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityModel.CustomerActivity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.ActivityModel.CustomerActivity prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.CustomerActivity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.ActivityModel.CustomerActivity, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.CustomerActivity)
        com.elarian.hera.proto.ActivityModel.CustomerActivityOrBuilder {
      // Construct using com.elarian.hera.proto.ActivityModel.CustomerActivity.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      @java.lang.Override
      public java.lang.String getKey() {
        return instance.getKey();
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getKeyBytes() {
        return instance.getKeyBytes();
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        copyOnWrite();
        instance.setKey(value);
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        copyOnWrite();
        instance.clearKey();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setKeyBytes(value);
        return this;
      }

      @java.lang.Override

      public int getPropertiesCount() {
        return instance.getPropertiesMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */
      @java.lang.Override

      public boolean containsProperties(
          java.lang.String key) {
        key.getClass();
        return instance.getPropertiesMap().containsKey(key);
      }

      public Builder clearProperties() {
        copyOnWrite();
        instance.getMutablePropertiesMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */

      public Builder removeProperties(
          java.lang.String key) {
        key.getClass();
        copyOnWrite();
        instance.getMutablePropertiesMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getPropertiesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getProperties() {
        return getPropertiesMap();
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getPropertiesMap());
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getPropertiesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getPropertiesMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getPropertiesOrThrow(
          java.lang.String key) {
        key.getClass();
        java.util.Map<java.lang.String, java.lang.String> map =
            instance.getPropertiesMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */
      public Builder putProperties(
          java.lang.String key,
          java.lang.String value) {
        key.getClass();
        value.getClass();
        copyOnWrite();
        instance.getMutablePropertiesMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; properties = 2;</code>
       */
      public Builder putAllProperties(
          java.util.Map<java.lang.String, java.lang.String> values) {
        copyOnWrite();
        instance.getMutablePropertiesMap().putAll(values);
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      @java.lang.Override
      public boolean hasCreatedAt() {
        return instance.hasCreatedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setCreatedAt(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeCreatedAt(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 3;</code>
       */
      public Builder clearCreatedAt() {  copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.CustomerActivity)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.ActivityModel.CustomerActivity();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "key_",
              "properties_",
              PropertiesDefaultEntryHolder.defaultEntry,
              "createdAt_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0001\u0000\u0000\u0001\u0208\u00022\u0003" +
                "\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.ActivityModel.CustomerActivity> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.ActivityModel.CustomerActivity.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.ActivityModel.CustomerActivity>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.CustomerActivity)
    private static final com.elarian.hera.proto.ActivityModel.CustomerActivity DEFAULT_INSTANCE;
    static {
      CustomerActivity defaultInstance = new CustomerActivity();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CustomerActivity.class, defaultInstance);
    }

    public static com.elarian.hera.proto.ActivityModel.CustomerActivity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CustomerActivity> PARSER;

    public static com.google.protobuf.Parser<CustomerActivity> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
