// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity_state.proto

package com.elarian.hera.proto;

public final class ActivityStateOuterClass {
  private ActivityStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ActivitySessionStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.ActivitySessionState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     * @return Whether the customerNumber field is set.
     */
    boolean hasCustomerNumber();
    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     * @return The customerNumber.
     */
    com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumber();

    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     * @return Whether the channelNumber field is set.
     */
    boolean hasChannelNumber();
    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     * @return The channelNumber.
     */
    com.elarian.hera.proto.ActivityModel.ActivityChannelNumber getChannelNumber();

    /**
     * <code>string session_id = 3;</code>
     * @return The sessionId.
     */
    java.lang.String getSessionId();
    /**
     * <code>string session_id = 3;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    /**
     * <code>string app_id = 4;</code>
     * @return The appId.
     */
    java.lang.String getAppId();
    /**
     * <code>string app_id = 4;</code>
     * @return The bytes for appId.
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    java.util.List<com.elarian.hera.proto.ActivityModel.CustomerActivity> 
        getActivitiesList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    com.elarian.hera.proto.ActivityModel.CustomerActivity getActivities(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    int getActivitiesCount();

    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return Whether the createdAt field is set.
     */
    boolean hasCreatedAt();
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     * @return The createdAt.
     */
    com.google.protobuf.Timestamp getCreatedAt();

    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     * @return Whether the updatedAt field is set.
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     * @return The updatedAt.
     */
    com.google.protobuf.Timestamp getUpdatedAt();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.ActivitySessionState}
   */
  public  static final class ActivitySessionState extends
      com.google.protobuf.GeneratedMessageLite<
          ActivitySessionState, ActivitySessionState.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.ActivitySessionState)
      ActivitySessionStateOrBuilder {
    private ActivitySessionState() {
      sessionId_ = "";
      appId_ = "";
      activities_ = emptyProtobufList();
    }
    public static final int CUSTOMER_NUMBER_FIELD_NUMBER = 1;
    private com.elarian.hera.proto.CommonModel.CustomerNumber customerNumber_;
    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     */
    @java.lang.Override
    public boolean hasCustomerNumber() {
      return customerNumber_ != null;
    }
    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumber() {
      return customerNumber_ == null ? com.elarian.hera.proto.CommonModel.CustomerNumber.getDefaultInstance() : customerNumber_;
    }
    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     */
    private void setCustomerNumber(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  customerNumber_ = value;
      
      }
    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCustomerNumber(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  if (customerNumber_ != null &&
          customerNumber_ != com.elarian.hera.proto.CommonModel.CustomerNumber.getDefaultInstance()) {
        customerNumber_ =
          com.elarian.hera.proto.CommonModel.CustomerNumber.newBuilder(customerNumber_).mergeFrom(value).buildPartial();
      } else {
        customerNumber_ = value;
      }
      
    }
    /**
     * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
     */
    private void clearCustomerNumber() {  customerNumber_ = null;
      
    }

    public static final int CHANNEL_NUMBER_FIELD_NUMBER = 2;
    private com.elarian.hera.proto.ActivityModel.ActivityChannelNumber channelNumber_;
    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     */
    @java.lang.Override
    public boolean hasChannelNumber() {
      return channelNumber_ != null;
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.ActivityModel.ActivityChannelNumber getChannelNumber() {
      return channelNumber_ == null ? com.elarian.hera.proto.ActivityModel.ActivityChannelNumber.getDefaultInstance() : channelNumber_;
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     */
    private void setChannelNumber(com.elarian.hera.proto.ActivityModel.ActivityChannelNumber value) {
      value.getClass();
  channelNumber_ = value;
      
      }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeChannelNumber(com.elarian.hera.proto.ActivityModel.ActivityChannelNumber value) {
      value.getClass();
  if (channelNumber_ != null &&
          channelNumber_ != com.elarian.hera.proto.ActivityModel.ActivityChannelNumber.getDefaultInstance()) {
        channelNumber_ =
          com.elarian.hera.proto.ActivityModel.ActivityChannelNumber.newBuilder(channelNumber_).mergeFrom(value).buildPartial();
      } else {
        channelNumber_ = value;
      }
      
    }
    /**
     * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
     */
    private void clearChannelNumber() {  channelNumber_ = null;
      
    }

    public static final int SESSION_ID_FIELD_NUMBER = 3;
    private java.lang.String sessionId_;
    /**
     * <code>string session_id = 3;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public java.lang.String getSessionId() {
      return sessionId_;
    }
    /**
     * <code>string session_id = 3;</code>
     * @return The bytes for sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sessionId_);
    }
    /**
     * <code>string session_id = 3;</code>
     * @param value The sessionId to set.
     */
    private void setSessionId(
        java.lang.String value) {
      value.getClass();
  
      sessionId_ = value;
    }
    /**
     * <code>string session_id = 3;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = getDefaultInstance().getSessionId();
    }
    /**
     * <code>string session_id = 3;</code>
     * @param value The bytes for sessionId to set.
     */
    private void setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      sessionId_ = value.toStringUtf8();
      
    }

    public static final int APP_ID_FIELD_NUMBER = 4;
    private java.lang.String appId_;
    /**
     * <code>string app_id = 4;</code>
     * @return The appId.
     */
    @java.lang.Override
    public java.lang.String getAppId() {
      return appId_;
    }
    /**
     * <code>string app_id = 4;</code>
     * @return The bytes for appId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(appId_);
    }
    /**
     * <code>string app_id = 4;</code>
     * @param value The appId to set.
     */
    private void setAppId(
        java.lang.String value) {
      value.getClass();
  
      appId_ = value;
    }
    /**
     * <code>string app_id = 4;</code>
     */
    private void clearAppId() {
      
      appId_ = getDefaultInstance().getAppId();
    }
    /**
     * <code>string app_id = 4;</code>
     * @param value The bytes for appId to set.
     */
    private void setAppIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      appId_ = value.toStringUtf8();
      
    }

    public static final int ACTIVITIES_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.ActivityModel.CustomerActivity> activities_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.ActivityModel.CustomerActivity> getActivitiesList() {
      return activities_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.ActivityModel.CustomerActivityOrBuilder> 
        getActivitiesOrBuilderList() {
      return activities_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    @java.lang.Override
    public int getActivitiesCount() {
      return activities_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.ActivityModel.CustomerActivity getActivities(int index) {
      return activities_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    public com.elarian.hera.proto.ActivityModel.CustomerActivityOrBuilder getActivitiesOrBuilder(
        int index) {
      return activities_.get(index);
    }
    private void ensureActivitiesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.ActivityModel.CustomerActivity> tmp = activities_;
      if (!tmp.isModifiable()) {
        activities_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    private void setActivities(
        int index, com.elarian.hera.proto.ActivityModel.CustomerActivity value) {
      value.getClass();
  ensureActivitiesIsMutable();
      activities_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    private void addActivities(com.elarian.hera.proto.ActivityModel.CustomerActivity value) {
      value.getClass();
  ensureActivitiesIsMutable();
      activities_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    private void addActivities(
        int index, com.elarian.hera.proto.ActivityModel.CustomerActivity value) {
      value.getClass();
  ensureActivitiesIsMutable();
      activities_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    private void addAllActivities(
        java.lang.Iterable<? extends com.elarian.hera.proto.ActivityModel.CustomerActivity> values) {
      ensureActivitiesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, activities_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    private void clearActivities() {
      activities_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
     */
    private void removeActivities(int index) {
      ensureActivitiesIsMutable();
      activities_.remove(index);
    }

    public static final int CREATED_AT_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp createdAt_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    private void setCreatedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  createdAt_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeCreatedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        createdAt_ =
          com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
      } else {
        createdAt_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 6;</code>
     */
    private void clearCreatedAt() {  createdAt_ = null;
      
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 7;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    private void setUpdatedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  updatedAt_ = value;
      
      }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      value.getClass();
  if (updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
        updatedAt_ =
          com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
      } else {
        updatedAt_ = value;
      }
      
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    private void clearUpdatedAt() {  updatedAt_ = null;
      
    }

    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.ActivitySessionState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.ActivitySessionState)
        com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionStateOrBuilder {
      // Construct using com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
       */
      @java.lang.Override
      public boolean hasCustomerNumber() {
        return instance.hasCustomerNumber();
      }
      /**
       * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumber() {
        return instance.getCustomerNumber();
      }
      /**
       * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
       */
      public Builder setCustomerNumber(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.setCustomerNumber(value);
        return this;
        }
      /**
       * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
       */
      public Builder setCustomerNumber(
          com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setCustomerNumber(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
       */
      public Builder mergeCustomerNumber(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.mergeCustomerNumber(value);
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.CustomerNumber customer_number = 1;</code>
       */
      public Builder clearCustomerNumber() {  copyOnWrite();
        instance.clearCustomerNumber();
        return this;
      }

      /**
       * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
       */
      @java.lang.Override
      public boolean hasChannelNumber() {
        return instance.hasChannelNumber();
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.ActivityModel.ActivityChannelNumber getChannelNumber() {
        return instance.getChannelNumber();
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
       */
      public Builder setChannelNumber(com.elarian.hera.proto.ActivityModel.ActivityChannelNumber value) {
        copyOnWrite();
        instance.setChannelNumber(value);
        return this;
        }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
       */
      public Builder setChannelNumber(
          com.elarian.hera.proto.ActivityModel.ActivityChannelNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setChannelNumber(builderForValue.build());
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
       */
      public Builder mergeChannelNumber(com.elarian.hera.proto.ActivityModel.ActivityChannelNumber value) {
        copyOnWrite();
        instance.mergeChannelNumber(value);
        return this;
      }
      /**
       * <code>.com.elarian.hera.proto.ActivityChannelNumber channel_number = 2;</code>
       */
      public Builder clearChannelNumber() {  copyOnWrite();
        instance.clearChannelNumber();
        return this;
      }

      /**
       * <code>string session_id = 3;</code>
       * @return The sessionId.
       */
      @java.lang.Override
      public java.lang.String getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <code>string session_id = 3;</code>
       * @return The bytes for sessionId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        return instance.getSessionIdBytes();
      }
      /**
       * <code>string session_id = 3;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <code>string session_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }
      /**
       * <code>string session_id = 3;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSessionIdBytes(value);
        return this;
      }

      /**
       * <code>string app_id = 4;</code>
       * @return The appId.
       */
      @java.lang.Override
      public java.lang.String getAppId() {
        return instance.getAppId();
      }
      /**
       * <code>string app_id = 4;</code>
       * @return The bytes for appId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        return instance.getAppIdBytes();
      }
      /**
       * <code>string app_id = 4;</code>
       * @param value The appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppId(
          java.lang.String value) {
        copyOnWrite();
        instance.setAppId(value);
        return this;
      }
      /**
       * <code>string app_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAppId() {
        copyOnWrite();
        instance.clearAppId();
        return this;
      }
      /**
       * <code>string app_id = 4;</code>
       * @param value The bytes for appId to set.
       * @return This builder for chaining.
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAppIdBytes(value);
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.ActivityModel.CustomerActivity> getActivitiesList() {
        return java.util.Collections.unmodifiableList(
            instance.getActivitiesList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      @java.lang.Override
      public int getActivitiesCount() {
        return instance.getActivitiesCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.ActivityModel.CustomerActivity getActivities(int index) {
        return instance.getActivities(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder setActivities(
          int index, com.elarian.hera.proto.ActivityModel.CustomerActivity value) {
        copyOnWrite();
        instance.setActivities(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder setActivities(
          int index, com.elarian.hera.proto.ActivityModel.CustomerActivity.Builder builderForValue) {
        copyOnWrite();
        instance.setActivities(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder addActivities(com.elarian.hera.proto.ActivityModel.CustomerActivity value) {
        copyOnWrite();
        instance.addActivities(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder addActivities(
          int index, com.elarian.hera.proto.ActivityModel.CustomerActivity value) {
        copyOnWrite();
        instance.addActivities(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder addActivities(
          com.elarian.hera.proto.ActivityModel.CustomerActivity.Builder builderForValue) {
        copyOnWrite();
        instance.addActivities(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder addActivities(
          int index, com.elarian.hera.proto.ActivityModel.CustomerActivity.Builder builderForValue) {
        copyOnWrite();
        instance.addActivities(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder addAllActivities(
          java.lang.Iterable<? extends com.elarian.hera.proto.ActivityModel.CustomerActivity> values) {
        copyOnWrite();
        instance.addAllActivities(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder clearActivities() {
        copyOnWrite();
        instance.clearActivities();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerActivity activities = 5;</code>
       */
      public Builder removeActivities(int index) {
        copyOnWrite();
        instance.removeActivities(index);
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      @java.lang.Override
      public boolean hasCreatedAt() {
        return instance.hasCreatedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getCreatedAt() {
        return instance.getCreatedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setCreatedAt(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder setCreatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setCreatedAt(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeCreatedAt(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_at = 6;</code>
       */
      public Builder clearCreatedAt() {  copyOnWrite();
        instance.clearCreatedAt();
        return this;
      }

      /**
       * <code>.google.protobuf.Timestamp updated_at = 7;</code>
       */
      @java.lang.Override
      public boolean hasUpdatedAt() {
        return instance.hasUpdatedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 7;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Timestamp getUpdatedAt() {
        return instance.getUpdatedAt();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 7;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.setUpdatedAt(value);
        return this;
        }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 7;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        copyOnWrite();
        instance.setUpdatedAt(builderForValue.build());
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 7;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        copyOnWrite();
        instance.mergeUpdatedAt(value);
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 7;</code>
       */
      public Builder clearUpdatedAt() {  copyOnWrite();
        instance.clearUpdatedAt();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.ActivitySessionState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "customerNumber_",
              "channelNumber_",
              "sessionId_",
              "appId_",
              "activities_",
              com.elarian.hera.proto.ActivityModel.CustomerActivity.class,
              "createdAt_",
              "updatedAt_",
            };
            java.lang.String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0001\u0000\u0001\t\u0002\t\u0003" +
                "\u0208\u0004\u0208\u0005\u001b\u0006\t\u0007\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.ActivitySessionState)
    private static final com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState DEFAULT_INSTANCE;
    static {
      ActivitySessionState defaultInstance = new ActivitySessionState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ActivitySessionState.class, defaultInstance);
    }

    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ActivitySessionState> PARSER;

    public static com.google.protobuf.Parser<ActivitySessionState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ActivityStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.ActivityState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    java.util.List<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> 
        getSessionsList();
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState getSessions(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    int getSessionsCount();

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    java.util.List<com.elarian.hera.proto.CommonModel.CustomerNumber> 
        getCustomerNumbersList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumbers(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    int getCustomerNumbersCount();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.ActivityState}
   */
  public  static final class ActivityState extends
      com.google.protobuf.GeneratedMessageLite<
          ActivityState, ActivityState.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.ActivityState)
      ActivityStateOrBuilder {
    private ActivityState() {
      sessions_ = emptyProtobufList();
      customerNumbers_ = emptyProtobufList();
    }
    public static final int SESSIONS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> sessions_;
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> getSessionsList() {
      return sessions_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionStateOrBuilder> 
        getSessionsOrBuilderList() {
      return sessions_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    @java.lang.Override
    public int getSessionsCount() {
      return sessions_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState getSessions(int index) {
      return sessions_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    public com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionStateOrBuilder getSessionsOrBuilder(
        int index) {
      return sessions_.get(index);
    }
    private void ensureSessionsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> tmp = sessions_;
      if (!tmp.isModifiable()) {
        sessions_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    private void setSessions(
        int index, com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState value) {
      value.getClass();
  ensureSessionsIsMutable();
      sessions_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    private void addSessions(com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState value) {
      value.getClass();
  ensureSessionsIsMutable();
      sessions_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    private void addSessions(
        int index, com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState value) {
      value.getClass();
  ensureSessionsIsMutable();
      sessions_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    private void addAllSessions(
        java.lang.Iterable<? extends com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> values) {
      ensureSessionsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, sessions_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    private void clearSessions() {
      sessions_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
     */
    private void removeSessions(int index) {
      ensureSessionsIsMutable();
      sessions_.remove(index);
    }

    public static final int CUSTOMER_NUMBERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerNumber> customerNumbers_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.CommonModel.CustomerNumber> getCustomerNumbersList() {
      return customerNumbers_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerNumberOrBuilder> 
        getCustomerNumbersOrBuilderList() {
      return customerNumbers_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    @java.lang.Override
    public int getCustomerNumbersCount() {
      return customerNumbers_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumbers(int index) {
      return customerNumbers_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    public com.elarian.hera.proto.CommonModel.CustomerNumberOrBuilder getCustomerNumbersOrBuilder(
        int index) {
      return customerNumbers_.get(index);
    }
    private void ensureCustomerNumbersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerNumber> tmp = customerNumbers_;
      if (!tmp.isModifiable()) {
        customerNumbers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    private void setCustomerNumbers(
        int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  ensureCustomerNumbersIsMutable();
      customerNumbers_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    private void addCustomerNumbers(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  ensureCustomerNumbersIsMutable();
      customerNumbers_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    private void addCustomerNumbers(
        int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  ensureCustomerNumbersIsMutable();
      customerNumbers_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    private void addAllCustomerNumbers(
        java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerNumber> values) {
      ensureCustomerNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, customerNumbers_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    private void clearCustomerNumbers() {
      customerNumbers_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
     */
    private void removeCustomerNumbers(int index) {
      ensureCustomerNumbersIsMutable();
      customerNumbers_.remove(index);
    }

    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.ActivityStateOuterClass.ActivityState prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.ActivityState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.ActivityStateOuterClass.ActivityState, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.ActivityState)
        com.elarian.hera.proto.ActivityStateOuterClass.ActivityStateOrBuilder {
      // Construct using com.elarian.hera.proto.ActivityStateOuterClass.ActivityState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> getSessionsList() {
        return java.util.Collections.unmodifiableList(
            instance.getSessionsList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      @java.lang.Override
      public int getSessionsCount() {
        return instance.getSessionsCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState getSessions(int index) {
        return instance.getSessions(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder setSessions(
          int index, com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState value) {
        copyOnWrite();
        instance.setSessions(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder setSessions(
          int index, com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState.Builder builderForValue) {
        copyOnWrite();
        instance.setSessions(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder addSessions(com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState value) {
        copyOnWrite();
        instance.addSessions(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder addSessions(
          int index, com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState value) {
        copyOnWrite();
        instance.addSessions(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder addSessions(
          com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState.Builder builderForValue) {
        copyOnWrite();
        instance.addSessions(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder addSessions(
          int index, com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState.Builder builderForValue) {
        copyOnWrite();
        instance.addSessions(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder addAllSessions(
          java.lang.Iterable<? extends com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState> values) {
        copyOnWrite();
        instance.addAllSessions(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder clearSessions() {
        copyOnWrite();
        instance.clearSessions();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.ActivitySessionState sessions = 1;</code>
       */
      public Builder removeSessions(int index) {
        copyOnWrite();
        instance.removeSessions(index);
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerNumber> getCustomerNumbersList() {
        return java.util.Collections.unmodifiableList(
            instance.getCustomerNumbersList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      @java.lang.Override
      public int getCustomerNumbersCount() {
        return instance.getCustomerNumbersCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumbers(int index) {
        return instance.getCustomerNumbers(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder setCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.setCustomerNumbers(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder setCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setCustomerNumbers(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder addCustomerNumbers(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.addCustomerNumbers(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder addCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.addCustomerNumbers(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder addCustomerNumbers(
          com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addCustomerNumbers(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder addCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addCustomerNumbers(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder addAllCustomerNumbers(
          java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerNumber> values) {
        copyOnWrite();
        instance.addAllCustomerNumbers(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder clearCustomerNumbers() {
        copyOnWrite();
        instance.clearCustomerNumbers();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 2;</code>
       */
      public Builder removeCustomerNumbers(int index) {
        copyOnWrite();
        instance.removeCustomerNumbers(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.ActivityState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.ActivityStateOuterClass.ActivityState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "sessions_",
              com.elarian.hera.proto.ActivityStateOuterClass.ActivitySessionState.class,
              "customerNumbers_",
              com.elarian.hera.proto.CommonModel.CustomerNumber.class,
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0002\u0000\u0001\u001b\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.ActivityStateOuterClass.ActivityState> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.ActivityStateOuterClass.ActivityState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.ActivityStateOuterClass.ActivityState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.ActivityState)
    private static final com.elarian.hera.proto.ActivityStateOuterClass.ActivityState DEFAULT_INSTANCE;
    static {
      ActivityState defaultInstance = new ActivityState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ActivityState.class, defaultInstance);
    }

    public static com.elarian.hera.proto.ActivityStateOuterClass.ActivityState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ActivityState> PARSER;

    public static com.google.protobuf.Parser<ActivityState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
