// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment_state.proto

package com.elarian.hera.proto;

public final class PaymentStateOuterClass {
  private PaymentStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PaymentStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.PaymentState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    java.util.List<com.elarian.hera.proto.CommonModel.CustomerNumber> 
        getCustomerNumbersList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumbers(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    int getCustomerNumbersCount();

    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    java.util.List<com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> 
        getChannelNumbersList();
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    com.elarian.hera.proto.PaymentModel.PaymentChannelNumber getChannelNumbers(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    int getChannelNumbersCount();

    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    java.util.List<com.elarian.hera.proto.PaymentModel.PaymentTransaction> 
        getTransactionLogList();
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    com.elarian.hera.proto.PaymentModel.PaymentTransaction getTransactionLog(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    int getTransactionLogCount();

    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    java.util.List<com.elarian.hera.proto.PaymentModel.PaymentTransaction> 
        getPendingTransactionsList();
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    com.elarian.hera.proto.PaymentModel.PaymentTransaction getPendingTransactions(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    int getPendingTransactionsCount();

    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    int getWalletsCount();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    boolean containsWallets(
        java.lang.String key);
    /**
     * Use {@link #getWalletsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance>
    getWallets();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance>
    getWalletsMap();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */

    com.elarian.hera.proto.PaymentModel.PaymentBalance getWalletsOrDefault(
        java.lang.String key,
        com.elarian.hera.proto.PaymentModel.PaymentBalance defaultValue);
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */

    com.elarian.hera.proto.PaymentModel.PaymentBalance getWalletsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.PaymentState}
   */
  public  static final class PaymentState extends
      com.google.protobuf.GeneratedMessageLite<
          PaymentState, PaymentState.Builder> implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.PaymentState)
      PaymentStateOrBuilder {
    private PaymentState() {
      customerNumbers_ = emptyProtobufList();
      channelNumbers_ = emptyProtobufList();
      transactionLog_ = emptyProtobufList();
      pendingTransactions_ = emptyProtobufList();
    }
    public static final int CUSTOMER_NUMBERS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerNumber> customerNumbers_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.CommonModel.CustomerNumber> getCustomerNumbersList() {
      return customerNumbers_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerNumberOrBuilder> 
        getCustomerNumbersOrBuilderList() {
      return customerNumbers_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    @java.lang.Override
    public int getCustomerNumbersCount() {
      return customerNumbers_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumbers(int index) {
      return customerNumbers_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    public com.elarian.hera.proto.CommonModel.CustomerNumberOrBuilder getCustomerNumbersOrBuilder(
        int index) {
      return customerNumbers_.get(index);
    }
    private void ensureCustomerNumbersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.CommonModel.CustomerNumber> tmp = customerNumbers_;
      if (!tmp.isModifiable()) {
        customerNumbers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    private void setCustomerNumbers(
        int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  ensureCustomerNumbersIsMutable();
      customerNumbers_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    private void addCustomerNumbers(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  ensureCustomerNumbersIsMutable();
      customerNumbers_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    private void addCustomerNumbers(
        int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
      value.getClass();
  ensureCustomerNumbersIsMutable();
      customerNumbers_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    private void addAllCustomerNumbers(
        java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerNumber> values) {
      ensureCustomerNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, customerNumbers_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    private void clearCustomerNumbers() {
      customerNumbers_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
     */
    private void removeCustomerNumbers(int index) {
      ensureCustomerNumbersIsMutable();
      customerNumbers_.remove(index);
    }

    public static final int CHANNEL_NUMBERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> channelNumbers_;
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> getChannelNumbersList() {
      return channelNumbers_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.PaymentModel.PaymentChannelNumberOrBuilder> 
        getChannelNumbersOrBuilderList() {
      return channelNumbers_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    @java.lang.Override
    public int getChannelNumbersCount() {
      return channelNumbers_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.PaymentModel.PaymentChannelNumber getChannelNumbers(int index) {
      return channelNumbers_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    public com.elarian.hera.proto.PaymentModel.PaymentChannelNumberOrBuilder getChannelNumbersOrBuilder(
        int index) {
      return channelNumbers_.get(index);
    }
    private void ensureChannelNumbersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> tmp = channelNumbers_;
      if (!tmp.isModifiable()) {
        channelNumbers_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    private void setChannelNumbers(
        int index, com.elarian.hera.proto.PaymentModel.PaymentChannelNumber value) {
      value.getClass();
  ensureChannelNumbersIsMutable();
      channelNumbers_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    private void addChannelNumbers(com.elarian.hera.proto.PaymentModel.PaymentChannelNumber value) {
      value.getClass();
  ensureChannelNumbersIsMutable();
      channelNumbers_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    private void addChannelNumbers(
        int index, com.elarian.hera.proto.PaymentModel.PaymentChannelNumber value) {
      value.getClass();
  ensureChannelNumbersIsMutable();
      channelNumbers_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    private void addAllChannelNumbers(
        java.lang.Iterable<? extends com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> values) {
      ensureChannelNumbersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, channelNumbers_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    private void clearChannelNumbers() {
      channelNumbers_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
     */
    private void removeChannelNumbers(int index) {
      ensureChannelNumbersIsMutable();
      channelNumbers_.remove(index);
    }

    public static final int TRANSACTION_LOG_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.PaymentModel.PaymentTransaction> transactionLog_;
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.PaymentModel.PaymentTransaction> getTransactionLogList() {
      return transactionLog_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.PaymentModel.PaymentTransactionOrBuilder> 
        getTransactionLogOrBuilderList() {
      return transactionLog_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    @java.lang.Override
    public int getTransactionLogCount() {
      return transactionLog_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.PaymentModel.PaymentTransaction getTransactionLog(int index) {
      return transactionLog_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    public com.elarian.hera.proto.PaymentModel.PaymentTransactionOrBuilder getTransactionLogOrBuilder(
        int index) {
      return transactionLog_.get(index);
    }
    private void ensureTransactionLogIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.PaymentModel.PaymentTransaction> tmp = transactionLog_;
      if (!tmp.isModifiable()) {
        transactionLog_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    private void setTransactionLog(
        int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
      value.getClass();
  ensureTransactionLogIsMutable();
      transactionLog_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    private void addTransactionLog(com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
      value.getClass();
  ensureTransactionLogIsMutable();
      transactionLog_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    private void addTransactionLog(
        int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
      value.getClass();
  ensureTransactionLogIsMutable();
      transactionLog_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    private void addAllTransactionLog(
        java.lang.Iterable<? extends com.elarian.hera.proto.PaymentModel.PaymentTransaction> values) {
      ensureTransactionLogIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, transactionLog_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    private void clearTransactionLog() {
      transactionLog_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
     */
    private void removeTransactionLog(int index) {
      ensureTransactionLogIsMutable();
      transactionLog_.remove(index);
    }

    public static final int PENDING_TRANSACTIONS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.PaymentModel.PaymentTransaction> pendingTransactions_;
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.PaymentModel.PaymentTransaction> getPendingTransactionsList() {
      return pendingTransactions_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    public java.util.List<? extends com.elarian.hera.proto.PaymentModel.PaymentTransactionOrBuilder> 
        getPendingTransactionsOrBuilderList() {
      return pendingTransactions_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    @java.lang.Override
    public int getPendingTransactionsCount() {
      return pendingTransactions_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.PaymentModel.PaymentTransaction getPendingTransactions(int index) {
      return pendingTransactions_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    public com.elarian.hera.proto.PaymentModel.PaymentTransactionOrBuilder getPendingTransactionsOrBuilder(
        int index) {
      return pendingTransactions_.get(index);
    }
    private void ensurePendingTransactionsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<com.elarian.hera.proto.PaymentModel.PaymentTransaction> tmp = pendingTransactions_;
      if (!tmp.isModifiable()) {
        pendingTransactions_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    private void setPendingTransactions(
        int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
      value.getClass();
  ensurePendingTransactionsIsMutable();
      pendingTransactions_.set(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    private void addPendingTransactions(com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
      value.getClass();
  ensurePendingTransactionsIsMutable();
      pendingTransactions_.add(value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    private void addPendingTransactions(
        int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
      value.getClass();
  ensurePendingTransactionsIsMutable();
      pendingTransactions_.add(index, value);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    private void addAllPendingTransactions(
        java.lang.Iterable<? extends com.elarian.hera.proto.PaymentModel.PaymentTransaction> values) {
      ensurePendingTransactionsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, pendingTransactions_);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    private void clearPendingTransactions() {
      pendingTransactions_ = emptyProtobufList();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
     */
    private void removePendingTransactions(int index) {
      ensurePendingTransactionsIsMutable();
      pendingTransactions_.remove(index);
    }

    public static final int WALLETS_FIELD_NUMBER = 5;
    private static final class WalletsDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.elarian.hera.proto.PaymentModel.PaymentBalance.getDefaultInstance());
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> wallets_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance>
    internalGetWallets() {
      return wallets_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance>
    internalGetMutableWallets() {
      if (!wallets_.isMutable()) {
        wallets_ = wallets_.mutableCopy();
      }
      return wallets_;
    }
    @java.lang.Override

    public int getWalletsCount() {
      return internalGetWallets().size();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    @java.lang.Override

    public boolean containsWallets(
        java.lang.String key) {
      key.getClass();
      return internalGetWallets().containsKey(key);
    }
    /**
     * Use {@link #getWalletsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> getWallets() {
      return getWalletsMap();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> getWalletsMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetWallets());
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    @java.lang.Override

    public com.elarian.hera.proto.PaymentModel.PaymentBalance getWalletsOrDefault(
        java.lang.String key,
        com.elarian.hera.proto.PaymentModel.PaymentBalance defaultValue) {
      key.getClass();
      java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> map =
          internalGetWallets();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    @java.lang.Override

    public com.elarian.hera.proto.PaymentModel.PaymentBalance getWalletsOrThrow(
        java.lang.String key) {
      key.getClass();
      java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> map =
          internalGetWallets();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
     */
    private java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance>
    getMutableWalletsMap() {
      return internalGetMutableWallets();
    }

    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.PaymentStateOuterClass.PaymentState prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.elarian.hera.proto.PaymentState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.elarian.hera.proto.PaymentStateOuterClass.PaymentState, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.PaymentState)
        com.elarian.hera.proto.PaymentStateOuterClass.PaymentStateOrBuilder {
      // Construct using com.elarian.hera.proto.PaymentStateOuterClass.PaymentState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerNumber> getCustomerNumbersList() {
        return java.util.Collections.unmodifiableList(
            instance.getCustomerNumbersList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      @java.lang.Override
      public int getCustomerNumbersCount() {
        return instance.getCustomerNumbersCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.CommonModel.CustomerNumber getCustomerNumbers(int index) {
        return instance.getCustomerNumbers(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder setCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.setCustomerNumbers(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder setCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setCustomerNumbers(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder addCustomerNumbers(com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.addCustomerNumbers(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder addCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber value) {
        copyOnWrite();
        instance.addCustomerNumbers(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder addCustomerNumbers(
          com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addCustomerNumbers(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder addCustomerNumbers(
          int index, com.elarian.hera.proto.CommonModel.CustomerNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addCustomerNumbers(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder addAllCustomerNumbers(
          java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerNumber> values) {
        copyOnWrite();
        instance.addAllCustomerNumbers(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder clearCustomerNumbers() {
        copyOnWrite();
        instance.clearCustomerNumbers();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerNumber customer_numbers = 1;</code>
       */
      public Builder removeCustomerNumbers(int index) {
        copyOnWrite();
        instance.removeCustomerNumbers(index);
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> getChannelNumbersList() {
        return java.util.Collections.unmodifiableList(
            instance.getChannelNumbersList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      @java.lang.Override
      public int getChannelNumbersCount() {
        return instance.getChannelNumbersCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.PaymentModel.PaymentChannelNumber getChannelNumbers(int index) {
        return instance.getChannelNumbers(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder setChannelNumbers(
          int index, com.elarian.hera.proto.PaymentModel.PaymentChannelNumber value) {
        copyOnWrite();
        instance.setChannelNumbers(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder setChannelNumbers(
          int index, com.elarian.hera.proto.PaymentModel.PaymentChannelNumber.Builder builderForValue) {
        copyOnWrite();
        instance.setChannelNumbers(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder addChannelNumbers(com.elarian.hera.proto.PaymentModel.PaymentChannelNumber value) {
        copyOnWrite();
        instance.addChannelNumbers(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder addChannelNumbers(
          int index, com.elarian.hera.proto.PaymentModel.PaymentChannelNumber value) {
        copyOnWrite();
        instance.addChannelNumbers(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder addChannelNumbers(
          com.elarian.hera.proto.PaymentModel.PaymentChannelNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addChannelNumbers(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder addChannelNumbers(
          int index, com.elarian.hera.proto.PaymentModel.PaymentChannelNumber.Builder builderForValue) {
        copyOnWrite();
        instance.addChannelNumbers(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder addAllChannelNumbers(
          java.lang.Iterable<? extends com.elarian.hera.proto.PaymentModel.PaymentChannelNumber> values) {
        copyOnWrite();
        instance.addAllChannelNumbers(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder clearChannelNumbers() {
        copyOnWrite();
        instance.clearChannelNumbers();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentChannelNumber channel_numbers = 2;</code>
       */
      public Builder removeChannelNumbers(int index) {
        copyOnWrite();
        instance.removeChannelNumbers(index);
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.PaymentModel.PaymentTransaction> getTransactionLogList() {
        return java.util.Collections.unmodifiableList(
            instance.getTransactionLogList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      @java.lang.Override
      public int getTransactionLogCount() {
        return instance.getTransactionLogCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.PaymentModel.PaymentTransaction getTransactionLog(int index) {
        return instance.getTransactionLog(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder setTransactionLog(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
        copyOnWrite();
        instance.setTransactionLog(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder setTransactionLog(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.setTransactionLog(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder addTransactionLog(com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
        copyOnWrite();
        instance.addTransactionLog(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder addTransactionLog(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
        copyOnWrite();
        instance.addTransactionLog(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder addTransactionLog(
          com.elarian.hera.proto.PaymentModel.PaymentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.addTransactionLog(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder addTransactionLog(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.addTransactionLog(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder addAllTransactionLog(
          java.lang.Iterable<? extends com.elarian.hera.proto.PaymentModel.PaymentTransaction> values) {
        copyOnWrite();
        instance.addAllTransactionLog(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder clearTransactionLog() {
        copyOnWrite();
        instance.clearTransactionLog();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction transaction_log = 3;</code>
       */
      public Builder removeTransactionLog(int index) {
        copyOnWrite();
        instance.removeTransactionLog(index);
        return this;
      }

      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      @java.lang.Override
      public java.util.List<com.elarian.hera.proto.PaymentModel.PaymentTransaction> getPendingTransactionsList() {
        return java.util.Collections.unmodifiableList(
            instance.getPendingTransactionsList());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      @java.lang.Override
      public int getPendingTransactionsCount() {
        return instance.getPendingTransactionsCount();
      }/**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      @java.lang.Override
      public com.elarian.hera.proto.PaymentModel.PaymentTransaction getPendingTransactions(int index) {
        return instance.getPendingTransactions(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder setPendingTransactions(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
        copyOnWrite();
        instance.setPendingTransactions(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder setPendingTransactions(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.setPendingTransactions(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder addPendingTransactions(com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
        copyOnWrite();
        instance.addPendingTransactions(value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder addPendingTransactions(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction value) {
        copyOnWrite();
        instance.addPendingTransactions(index, value);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder addPendingTransactions(
          com.elarian.hera.proto.PaymentModel.PaymentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.addPendingTransactions(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder addPendingTransactions(
          int index, com.elarian.hera.proto.PaymentModel.PaymentTransaction.Builder builderForValue) {
        copyOnWrite();
        instance.addPendingTransactions(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder addAllPendingTransactions(
          java.lang.Iterable<? extends com.elarian.hera.proto.PaymentModel.PaymentTransaction> values) {
        copyOnWrite();
        instance.addAllPendingTransactions(values);
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder clearPendingTransactions() {
        copyOnWrite();
        instance.clearPendingTransactions();
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.PaymentTransaction pending_transactions = 4;</code>
       */
      public Builder removePendingTransactions(int index) {
        copyOnWrite();
        instance.removePendingTransactions(index);
        return this;
      }

      @java.lang.Override

      public int getWalletsCount() {
        return instance.getWalletsMap().size();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */
      @java.lang.Override

      public boolean containsWallets(
          java.lang.String key) {
        key.getClass();
        return instance.getWalletsMap().containsKey(key);
      }

      public Builder clearWallets() {
        copyOnWrite();
        instance.getMutableWalletsMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */

      public Builder removeWallets(
          java.lang.String key) {
        key.getClass();
        copyOnWrite();
        instance.getMutableWalletsMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getWalletsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> getWallets() {
        return getWalletsMap();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> getWalletsMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getWalletsMap());
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */
      @java.lang.Override

      public com.elarian.hera.proto.PaymentModel.PaymentBalance getWalletsOrDefault(
          java.lang.String key,
          com.elarian.hera.proto.PaymentModel.PaymentBalance defaultValue) {
        key.getClass();
        java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> map =
            instance.getWalletsMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */
      @java.lang.Override

      public com.elarian.hera.proto.PaymentModel.PaymentBalance getWalletsOrThrow(
          java.lang.String key) {
        key.getClass();
        java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> map =
            instance.getWalletsMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */
      public Builder putWallets(
          java.lang.String key,
          com.elarian.hera.proto.PaymentModel.PaymentBalance value) {
        key.getClass();
        value.getClass();
        copyOnWrite();
        instance.getMutableWalletsMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.PaymentBalance&gt; wallets = 5;</code>
       */
      public Builder putAllWallets(
          java.util.Map<java.lang.String, com.elarian.hera.proto.PaymentModel.PaymentBalance> values) {
        copyOnWrite();
        instance.getMutableWalletsMap().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.PaymentState)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.elarian.hera.proto.PaymentStateOuterClass.PaymentState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "customerNumbers_",
              com.elarian.hera.proto.CommonModel.CustomerNumber.class,
              "channelNumbers_",
              com.elarian.hera.proto.PaymentModel.PaymentChannelNumber.class,
              "transactionLog_",
              com.elarian.hera.proto.PaymentModel.PaymentTransaction.class,
              "pendingTransactions_",
              com.elarian.hera.proto.PaymentModel.PaymentTransaction.class,
              "wallets_",
              WalletsDefaultEntryHolder.defaultEntry,
            };
            java.lang.String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0001\u0004\u0000\u0001\u001b\u0002\u001b" +
                "\u0003\u001b\u0004\u001b\u00052";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.elarian.hera.proto.PaymentStateOuterClass.PaymentState> parser = PARSER;
          if (parser == null) {
            synchronized (com.elarian.hera.proto.PaymentStateOuterClass.PaymentState.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.elarian.hera.proto.PaymentStateOuterClass.PaymentState>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.PaymentState)
    private static final com.elarian.hera.proto.PaymentStateOuterClass.PaymentState DEFAULT_INSTANCE;
    static {
      PaymentState defaultInstance = new PaymentState();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PaymentState.class, defaultInstance);
    }

    public static com.elarian.hera.proto.PaymentStateOuterClass.PaymentState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PaymentState> PARSER;

    public static com.google.protobuf.Parser<PaymentState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
