// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_model.proto

package com.elarian.hera.proto;

public final class AppModel {
  private AppModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerReminderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.CustomerReminder)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>.google.protobuf.Timestamp remind_at = 2;</code>
     * @return Whether the remindAt field is set.
     */
    boolean hasRemindAt();
    /**
     * <code>.google.protobuf.Timestamp remind_at = 2;</code>
     * @return The remindAt.
     */
    com.google.protobuf.Timestamp getRemindAt();
    /**
     * <code>.google.protobuf.Timestamp remind_at = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getRemindAtOrBuilder();

    /**
     * <code>.google.protobuf.Duration interval = 3;</code>
     * @return Whether the interval field is set.
     */
    boolean hasInterval();
    /**
     * <code>.google.protobuf.Duration interval = 3;</code>
     * @return The interval.
     */
    com.google.protobuf.Duration getInterval();
    /**
     * <code>.google.protobuf.Duration interval = 3;</code>
     */
    com.google.protobuf.DurationOrBuilder getIntervalOrBuilder();

    /**
     * <code>.google.protobuf.StringValue payload = 4;</code>
     * @return Whether the payload field is set.
     */
    boolean hasPayload();
    /**
     * <code>.google.protobuf.StringValue payload = 4;</code>
     * @return The payload.
     */
    com.google.protobuf.StringValue getPayload();
    /**
     * <code>.google.protobuf.StringValue payload = 4;</code>
     */
    com.google.protobuf.StringValueOrBuilder getPayloadOrBuilder();
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.CustomerReminder}
   */
  public static final class CustomerReminder extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.CustomerReminder)
      CustomerReminderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomerReminder.newBuilder() to construct.
    private CustomerReminder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomerReminder() {
      key_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomerReminder();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomerReminder(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (remindAt_ != null) {
                subBuilder = remindAt_.toBuilder();
              }
              remindAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(remindAt_);
                remindAt_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Duration.Builder subBuilder = null;
              if (interval_ != null) {
                subBuilder = interval_.toBuilder();
              }
              interval_ = input.readMessage(com.google.protobuf.Duration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(interval_);
                interval_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (payload_ != null) {
                subBuilder = payload_.toBuilder();
              }
              payload_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payload_);
                payload_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elarian.hera.proto.AppModel.internal_static_com_elarian_hera_proto_CustomerReminder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elarian.hera.proto.AppModel.internal_static_com_elarian_hera_proto_CustomerReminder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elarian.hera.proto.AppModel.CustomerReminder.class, com.elarian.hera.proto.AppModel.CustomerReminder.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REMIND_AT_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp remindAt_;
    /**
     * <code>.google.protobuf.Timestamp remind_at = 2;</code>
     * @return Whether the remindAt field is set.
     */
    @java.lang.Override
    public boolean hasRemindAt() {
      return remindAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp remind_at = 2;</code>
     * @return The remindAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getRemindAt() {
      return remindAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : remindAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp remind_at = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getRemindAtOrBuilder() {
      return getRemindAt();
    }

    public static final int INTERVAL_FIELD_NUMBER = 3;
    private com.google.protobuf.Duration interval_;
    /**
     * <code>.google.protobuf.Duration interval = 3;</code>
     * @return Whether the interval field is set.
     */
    @java.lang.Override
    public boolean hasInterval() {
      return interval_ != null;
    }
    /**
     * <code>.google.protobuf.Duration interval = 3;</code>
     * @return The interval.
     */
    @java.lang.Override
    public com.google.protobuf.Duration getInterval() {
      return interval_ == null ? com.google.protobuf.Duration.getDefaultInstance() : interval_;
    }
    /**
     * <code>.google.protobuf.Duration interval = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DurationOrBuilder getIntervalOrBuilder() {
      return getInterval();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.StringValue payload_;
    /**
     * <code>.google.protobuf.StringValue payload = 4;</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return payload_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue payload = 4;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.StringValue getPayload() {
      return payload_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : payload_;
    }
    /**
     * <code>.google.protobuf.StringValue payload = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StringValueOrBuilder getPayloadOrBuilder() {
      return getPayload();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (remindAt_ != null) {
        output.writeMessage(2, getRemindAt());
      }
      if (interval_ != null) {
        output.writeMessage(3, getInterval());
      }
      if (payload_ != null) {
        output.writeMessage(4, getPayload());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (remindAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRemindAt());
      }
      if (interval_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getInterval());
      }
      if (payload_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPayload());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elarian.hera.proto.AppModel.CustomerReminder)) {
        return super.equals(obj);
      }
      com.elarian.hera.proto.AppModel.CustomerReminder other = (com.elarian.hera.proto.AppModel.CustomerReminder) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (hasRemindAt() != other.hasRemindAt()) return false;
      if (hasRemindAt()) {
        if (!getRemindAt()
            .equals(other.getRemindAt())) return false;
      }
      if (hasInterval() != other.hasInterval()) return false;
      if (hasInterval()) {
        if (!getInterval()
            .equals(other.getInterval())) return false;
      }
      if (hasPayload() != other.hasPayload()) return false;
      if (hasPayload()) {
        if (!getPayload()
            .equals(other.getPayload())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      if (hasRemindAt()) {
        hash = (37 * hash) + REMIND_AT_FIELD_NUMBER;
        hash = (53 * hash) + getRemindAt().hashCode();
      }
      if (hasInterval()) {
        hash = (37 * hash) + INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + getInterval().hashCode();
      }
      if (hasPayload()) {
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elarian.hera.proto.AppModel.CustomerReminder parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.AppModel.CustomerReminder prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elarian.hera.proto.CustomerReminder}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.CustomerReminder)
        com.elarian.hera.proto.AppModel.CustomerReminderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elarian.hera.proto.AppModel.internal_static_com_elarian_hera_proto_CustomerReminder_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elarian.hera.proto.AppModel.internal_static_com_elarian_hera_proto_CustomerReminder_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elarian.hera.proto.AppModel.CustomerReminder.class, com.elarian.hera.proto.AppModel.CustomerReminder.Builder.class);
      }

      // Construct using com.elarian.hera.proto.AppModel.CustomerReminder.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        key_ = "";

        if (remindAtBuilder_ == null) {
          remindAt_ = null;
        } else {
          remindAt_ = null;
          remindAtBuilder_ = null;
        }
        if (intervalBuilder_ == null) {
          interval_ = null;
        } else {
          interval_ = null;
          intervalBuilder_ = null;
        }
        if (payloadBuilder_ == null) {
          payload_ = null;
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elarian.hera.proto.AppModel.internal_static_com_elarian_hera_proto_CustomerReminder_descriptor;
      }

      @java.lang.Override
      public com.elarian.hera.proto.AppModel.CustomerReminder getDefaultInstanceForType() {
        return com.elarian.hera.proto.AppModel.CustomerReminder.getDefaultInstance();
      }

      @java.lang.Override
      public com.elarian.hera.proto.AppModel.CustomerReminder build() {
        com.elarian.hera.proto.AppModel.CustomerReminder result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.elarian.hera.proto.AppModel.CustomerReminder buildPartial() {
        com.elarian.hera.proto.AppModel.CustomerReminder result = new com.elarian.hera.proto.AppModel.CustomerReminder(this);
        result.key_ = key_;
        if (remindAtBuilder_ == null) {
          result.remindAt_ = remindAt_;
        } else {
          result.remindAt_ = remindAtBuilder_.build();
        }
        if (intervalBuilder_ == null) {
          result.interval_ = interval_;
        } else {
          result.interval_ = intervalBuilder_.build();
        }
        if (payloadBuilder_ == null) {
          result.payload_ = payload_;
        } else {
          result.payload_ = payloadBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elarian.hera.proto.AppModel.CustomerReminder) {
          return mergeFrom((com.elarian.hera.proto.AppModel.CustomerReminder)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elarian.hera.proto.AppModel.CustomerReminder other) {
        if (other == com.elarian.hera.proto.AppModel.CustomerReminder.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.hasRemindAt()) {
          mergeRemindAt(other.getRemindAt());
        }
        if (other.hasInterval()) {
          mergeInterval(other.getInterval());
        }
        if (other.hasPayload()) {
          mergePayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elarian.hera.proto.AppModel.CustomerReminder parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elarian.hera.proto.AppModel.CustomerReminder) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp remindAt_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> remindAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       * @return Whether the remindAt field is set.
       */
      public boolean hasRemindAt() {
        return remindAtBuilder_ != null || remindAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       * @return The remindAt.
       */
      public com.google.protobuf.Timestamp getRemindAt() {
        if (remindAtBuilder_ == null) {
          return remindAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : remindAt_;
        } else {
          return remindAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      public Builder setRemindAt(com.google.protobuf.Timestamp value) {
        if (remindAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          remindAt_ = value;
          onChanged();
        } else {
          remindAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      public Builder setRemindAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (remindAtBuilder_ == null) {
          remindAt_ = builderForValue.build();
          onChanged();
        } else {
          remindAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      public Builder mergeRemindAt(com.google.protobuf.Timestamp value) {
        if (remindAtBuilder_ == null) {
          if (remindAt_ != null) {
            remindAt_ =
              com.google.protobuf.Timestamp.newBuilder(remindAt_).mergeFrom(value).buildPartial();
          } else {
            remindAt_ = value;
          }
          onChanged();
        } else {
          remindAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      public Builder clearRemindAt() {
        if (remindAtBuilder_ == null) {
          remindAt_ = null;
          onChanged();
        } else {
          remindAt_ = null;
          remindAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getRemindAtBuilder() {
        
        onChanged();
        return getRemindAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getRemindAtOrBuilder() {
        if (remindAtBuilder_ != null) {
          return remindAtBuilder_.getMessageOrBuilder();
        } else {
          return remindAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : remindAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp remind_at = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getRemindAtFieldBuilder() {
        if (remindAtBuilder_ == null) {
          remindAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getRemindAt(),
                  getParentForChildren(),
                  isClean());
          remindAt_ = null;
        }
        return remindAtBuilder_;
      }

      private com.google.protobuf.Duration interval_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> intervalBuilder_;
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       * @return Whether the interval field is set.
       */
      public boolean hasInterval() {
        return intervalBuilder_ != null || interval_ != null;
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       * @return The interval.
       */
      public com.google.protobuf.Duration getInterval() {
        if (intervalBuilder_ == null) {
          return interval_ == null ? com.google.protobuf.Duration.getDefaultInstance() : interval_;
        } else {
          return intervalBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      public Builder setInterval(com.google.protobuf.Duration value) {
        if (intervalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          interval_ = value;
          onChanged();
        } else {
          intervalBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      public Builder setInterval(
          com.google.protobuf.Duration.Builder builderForValue) {
        if (intervalBuilder_ == null) {
          interval_ = builderForValue.build();
          onChanged();
        } else {
          intervalBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      public Builder mergeInterval(com.google.protobuf.Duration value) {
        if (intervalBuilder_ == null) {
          if (interval_ != null) {
            interval_ =
              com.google.protobuf.Duration.newBuilder(interval_).mergeFrom(value).buildPartial();
          } else {
            interval_ = value;
          }
          onChanged();
        } else {
          intervalBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      public Builder clearInterval() {
        if (intervalBuilder_ == null) {
          interval_ = null;
          onChanged();
        } else {
          interval_ = null;
          intervalBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      public com.google.protobuf.Duration.Builder getIntervalBuilder() {
        
        onChanged();
        return getIntervalFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      public com.google.protobuf.DurationOrBuilder getIntervalOrBuilder() {
        if (intervalBuilder_ != null) {
          return intervalBuilder_.getMessageOrBuilder();
        } else {
          return interval_ == null ?
              com.google.protobuf.Duration.getDefaultInstance() : interval_;
        }
      }
      /**
       * <code>.google.protobuf.Duration interval = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
          getIntervalFieldBuilder() {
        if (intervalBuilder_ == null) {
          intervalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                  getInterval(),
                  getParentForChildren(),
                  isClean());
          interval_ = null;
        }
        return intervalBuilder_;
      }

      private com.google.protobuf.StringValue payload_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> payloadBuilder_;
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       * @return Whether the payload field is set.
       */
      public boolean hasPayload() {
        return payloadBuilder_ != null || payload_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       * @return The payload.
       */
      public com.google.protobuf.StringValue getPayload() {
        if (payloadBuilder_ == null) {
          return payload_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : payload_;
        } else {
          return payloadBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      public Builder setPayload(com.google.protobuf.StringValue value) {
        if (payloadBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          payloadBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      public Builder setPayload(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (payloadBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          payloadBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      public Builder mergePayload(com.google.protobuf.StringValue value) {
        if (payloadBuilder_ == null) {
          if (payload_ != null) {
            payload_ =
              com.google.protobuf.StringValue.newBuilder(payload_).mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          payloadBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      public Builder clearPayload() {
        if (payloadBuilder_ == null) {
          payload_ = null;
          onChanged();
        } else {
          payload_ = null;
          payloadBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      public com.google.protobuf.StringValue.Builder getPayloadBuilder() {
        
        onChanged();
        return getPayloadFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getPayloadOrBuilder() {
        if (payloadBuilder_ != null) {
          return payloadBuilder_.getMessageOrBuilder();
        } else {
          return payload_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : payload_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue payload = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getPayloadFieldBuilder() {
        if (payloadBuilder_ == null) {
          payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getPayload(),
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        return payloadBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.CustomerReminder)
    }

    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.CustomerReminder)
    private static final com.elarian.hera.proto.AppModel.CustomerReminder DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elarian.hera.proto.AppModel.CustomerReminder();
    }

    public static com.elarian.hera.proto.AppModel.CustomerReminder getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomerReminder>
        PARSER = new com.google.protobuf.AbstractParser<CustomerReminder>() {
      @java.lang.Override
      public CustomerReminder parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerReminder(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomerReminder> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CustomerReminder> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.elarian.hera.proto.AppModel.CustomerReminder getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elarian_hera_proto_CustomerReminder_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elarian_hera_proto_CustomerReminder_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017app_model.proto\022\026com.elarian.hera.prot" +
      "o\032\036google/protobuf/wrappers.proto\032\036googl" +
      "e/protobuf/duration.proto\032\037google/protob" +
      "uf/timestamp.proto\"\252\001\n\020CustomerReminder\022" +
      "\013\n\003key\030\001 \001(\t\022-\n\tremind_at\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\022+\n\010interval\030\003 \001(\0132\031." +
      "google.protobuf.Duration\022-\n\007payload\030\004 \001(" +
      "\0132\034.google.protobuf.StringValueb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_elarian_hera_proto_CustomerReminder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_elarian_hera_proto_CustomerReminder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elarian_hera_proto_CustomerReminder_descriptor,
        new java.lang.String[] { "Key", "RemindAt", "Interval", "Payload", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
