// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity_state.proto

package com.elarian.hera.proto;

public final class IdentityStateOuterClass {
  private IdentityStateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentityStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.elarian.hera.proto.IdentityState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> 
        getTagsList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerIndex getTags(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
        getTagsOrBuilderList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getTagsOrBuilder(
        int index);

    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    int getMetadataCount();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    boolean containsMetadata(
        java.lang.String key);
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    getMetadata();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    getMetadataMap();
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */

    com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrDefault(
        java.lang.String key,
        com.elarian.hera.proto.CommonModel.DataMapValue defaultValue);
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */

    com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrThrow(
        java.lang.String key);

    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> 
        getSecondaryIdsList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerIndex getSecondaryIds(int index);
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    int getSecondaryIdsCount();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
        getSecondaryIdsOrBuilderList();
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getSecondaryIdsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.elarian.hera.proto.IdentityState}
   */
  public static final class IdentityState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.elarian.hera.proto.IdentityState)
      IdentityStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdentityState.newBuilder() to construct.
    private IdentityState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdentityState() {
      tags_ = java.util.Collections.emptyList();
      secondaryIds_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdentityState();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IdentityState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                tags_ = new java.util.ArrayList<com.elarian.hera.proto.CommonModel.CustomerIndex>();
                mutable_bitField0_ |= 0x00000001;
              }
              tags_.add(
                  input.readMessage(com.elarian.hera.proto.CommonModel.CustomerIndex.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                metadata_ = com.google.protobuf.MapField.newMapField(
                    MetadataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              metadata_.getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                secondaryIds_ = new java.util.ArrayList<com.elarian.hera.proto.CommonModel.CustomerIndex>();
                mutable_bitField0_ |= 0x00000004;
              }
              secondaryIds_.add(
                  input.readMessage(com.elarian.hera.proto.CommonModel.CustomerIndex.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          tags_ = java.util.Collections.unmodifiableList(tags_);
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          secondaryIds_ = java.util.Collections.unmodifiableList(secondaryIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.elarian.hera.proto.IdentityStateOuterClass.internal_static_com_elarian_hera_proto_IdentityState_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.elarian.hera.proto.IdentityStateOuterClass.internal_static_com_elarian_hera_proto_IdentityState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.class, com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.Builder.class);
    }

    public static final int TAGS_FIELD_NUMBER = 1;
    private java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> tags_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerIndex getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    public static final int METADATA_FIELD_NUMBER = 2;
    private static final class MetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>newDefaultInstance(
                  com.elarian.hera.proto.IdentityStateOuterClass.internal_static_com_elarian_hera_proto_IdentityState_MetadataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.elarian.hera.proto.CommonModel.DataMapValue.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> metadata_;
    private com.google.protobuf.MapField<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
    internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }

    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */

    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrDefault(
        java.lang.String key,
        com.elarian.hera.proto.CommonModel.DataMapValue defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
     */
    @java.lang.Override

    public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int SECONDARY_IDS_FIELD_NUMBER = 3;
    private java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> secondaryIds_;
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getSecondaryIdsList() {
      return secondaryIds_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
        getSecondaryIdsOrBuilderList() {
      return secondaryIds_;
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public int getSecondaryIdsCount() {
      return secondaryIds_.size();
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerIndex getSecondaryIds(int index) {
      return secondaryIds_.get(index);
    }
    /**
     * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
     */
    @java.lang.Override
    public com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getSecondaryIdsOrBuilder(
        int index) {
      return secondaryIds_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(1, tags_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetadata(),
          MetadataDefaultEntryHolder.defaultEntry,
          2);
      for (int i = 0; i < secondaryIds_.size(); i++) {
        output.writeMessage(3, secondaryIds_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tags_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> entry
           : internalGetMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
        metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, metadata__);
      }
      for (int i = 0; i < secondaryIds_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, secondaryIds_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.elarian.hera.proto.IdentityStateOuterClass.IdentityState)) {
        return super.equals(obj);
      }
      com.elarian.hera.proto.IdentityStateOuterClass.IdentityState other = (com.elarian.hera.proto.IdentityStateOuterClass.IdentityState) obj;

      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (!internalGetMetadata().equals(
          other.internalGetMetadata())) return false;
      if (!getSecondaryIdsList()
          .equals(other.getSecondaryIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      if (!internalGetMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetadata().hashCode();
      }
      if (getSecondaryIdsCount() > 0) {
        hash = (37 * hash) + SECONDARY_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getSecondaryIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.elarian.hera.proto.IdentityStateOuterClass.IdentityState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.elarian.hera.proto.IdentityState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.elarian.hera.proto.IdentityState)
        com.elarian.hera.proto.IdentityStateOuterClass.IdentityStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.elarian.hera.proto.IdentityStateOuterClass.internal_static_com_elarian_hera_proto_IdentityState_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.elarian.hera.proto.IdentityStateOuterClass.internal_static_com_elarian_hera_proto_IdentityState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.class, com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.Builder.class);
      }

      // Construct using com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTagsFieldBuilder();
          getSecondaryIdsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tagsBuilder_.clear();
        }
        internalGetMutableMetadata().clear();
        if (secondaryIdsBuilder_ == null) {
          secondaryIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          secondaryIdsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.elarian.hera.proto.IdentityStateOuterClass.internal_static_com_elarian_hera_proto_IdentityState_descriptor;
      }

      @java.lang.Override
      public com.elarian.hera.proto.IdentityStateOuterClass.IdentityState getDefaultInstanceForType() {
        return com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.getDefaultInstance();
      }

      @java.lang.Override
      public com.elarian.hera.proto.IdentityStateOuterClass.IdentityState build() {
        com.elarian.hera.proto.IdentityStateOuterClass.IdentityState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.elarian.hera.proto.IdentityStateOuterClass.IdentityState buildPartial() {
        com.elarian.hera.proto.IdentityStateOuterClass.IdentityState result = new com.elarian.hera.proto.IdentityStateOuterClass.IdentityState(this);
        int from_bitField0_ = bitField0_;
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
        if (secondaryIdsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)) {
            secondaryIds_ = java.util.Collections.unmodifiableList(secondaryIds_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.secondaryIds_ = secondaryIds_;
        } else {
          result.secondaryIds_ = secondaryIdsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.elarian.hera.proto.IdentityStateOuterClass.IdentityState) {
          return mergeFrom((com.elarian.hera.proto.IdentityStateOuterClass.IdentityState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.elarian.hera.proto.IdentityStateOuterClass.IdentityState other) {
        if (other == com.elarian.hera.proto.IdentityStateOuterClass.IdentityState.getDefaultInstance()) return this;
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        internalGetMutableMetadata().mergeFrom(
            other.internalGetMetadata());
        if (secondaryIdsBuilder_ == null) {
          if (!other.secondaryIds_.isEmpty()) {
            if (secondaryIds_.isEmpty()) {
              secondaryIds_ = other.secondaryIds_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSecondaryIdsIsMutable();
              secondaryIds_.addAll(other.secondaryIds_);
            }
            onChanged();
          }
        } else {
          if (!other.secondaryIds_.isEmpty()) {
            if (secondaryIdsBuilder_.isEmpty()) {
              secondaryIdsBuilder_.dispose();
              secondaryIdsBuilder_ = null;
              secondaryIds_ = other.secondaryIds_;
              bitField0_ = (bitField0_ & ~0x00000004);
              secondaryIdsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSecondaryIdsFieldBuilder() : null;
            } else {
              secondaryIdsBuilder_.addAllMessages(other.secondaryIds_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.elarian.hera.proto.IdentityStateOuterClass.IdentityState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.elarian.hera.proto.IdentityStateOuterClass.IdentityState) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tags_ = new java.util.ArrayList<com.elarian.hera.proto.CommonModel.CustomerIndex>(tags_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.elarian.hera.proto.CommonModel.CustomerIndex, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder, com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder setTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder setTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(
          com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addTags(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerIndex> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            com.elarian.hera.proto.CommonModel.CustomerIndex.getDefaultInstance());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, com.elarian.hera.proto.CommonModel.CustomerIndex.getDefaultInstance());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex tags = 1;</code>
       */
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.elarian.hera.proto.CommonModel.CustomerIndex, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder, com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.elarian.hera.proto.CommonModel.CustomerIndex, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder, com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> metadata_;
      private com.google.protobuf.MapField<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
      internalGetMetadata() {
        if (metadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        return metadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
      internalGetMutableMetadata() {
        onChanged();;
        if (metadata_ == null) {
          metadata_ = com.google.protobuf.MapField.newMapField(
              MetadataDefaultEntryHolder.defaultEntry);
        }
        if (!metadata_.isMutable()) {
          metadata_ = metadata_.copy();
        }
        return metadata_;
      }

      public int getMetadataCount() {
        return internalGetMetadata().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */

      @java.lang.Override
      public boolean containsMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadata() {
        return getMetadataMap();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> getMetadataMap() {
        return internalGetMetadata().getMap();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override

      public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrDefault(
          java.lang.String key,
          com.elarian.hera.proto.CommonModel.DataMapValue defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
            internalGetMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      @java.lang.Override

      public com.elarian.hera.proto.CommonModel.DataMapValue getMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> map =
            internalGetMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMetadata() {
        internalGetMutableMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */

      public Builder removeMetadata(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue>
      getMutableMetadata() {
        return internalGetMutableMetadata().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */
      public Builder putMetadata(
          java.lang.String key,
          com.elarian.hera.proto.CommonModel.DataMapValue value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMetadata().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .com.elarian.hera.proto.DataMapValue&gt; metadata = 2;</code>
       */

      public Builder putAllMetadata(
          java.util.Map<java.lang.String, com.elarian.hera.proto.CommonModel.DataMapValue> values) {
        internalGetMutableMetadata().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> secondaryIds_ =
        java.util.Collections.emptyList();
      private void ensureSecondaryIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          secondaryIds_ = new java.util.ArrayList<com.elarian.hera.proto.CommonModel.CustomerIndex>(secondaryIds_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.elarian.hera.proto.CommonModel.CustomerIndex, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder, com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> secondaryIdsBuilder_;

      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex> getSecondaryIdsList() {
        if (secondaryIdsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(secondaryIds_);
        } else {
          return secondaryIdsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public int getSecondaryIdsCount() {
        if (secondaryIdsBuilder_ == null) {
          return secondaryIds_.size();
        } else {
          return secondaryIdsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex getSecondaryIds(int index) {
        if (secondaryIdsBuilder_ == null) {
          return secondaryIds_.get(index);
        } else {
          return secondaryIdsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder setSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        if (secondaryIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecondaryIdsIsMutable();
          secondaryIds_.set(index, value);
          onChanged();
        } else {
          secondaryIdsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder setSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        if (secondaryIdsBuilder_ == null) {
          ensureSecondaryIdsIsMutable();
          secondaryIds_.set(index, builderForValue.build());
          onChanged();
        } else {
          secondaryIdsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        if (secondaryIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecondaryIdsIsMutable();
          secondaryIds_.add(value);
          onChanged();
        } else {
          secondaryIdsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex value) {
        if (secondaryIdsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSecondaryIdsIsMutable();
          secondaryIds_.add(index, value);
          onChanged();
        } else {
          secondaryIdsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(
          com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        if (secondaryIdsBuilder_ == null) {
          ensureSecondaryIdsIsMutable();
          secondaryIds_.add(builderForValue.build());
          onChanged();
        } else {
          secondaryIdsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addSecondaryIds(
          int index, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder builderForValue) {
        if (secondaryIdsBuilder_ == null) {
          ensureSecondaryIdsIsMutable();
          secondaryIds_.add(index, builderForValue.build());
          onChanged();
        } else {
          secondaryIdsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder addAllSecondaryIds(
          java.lang.Iterable<? extends com.elarian.hera.proto.CommonModel.CustomerIndex> values) {
        if (secondaryIdsBuilder_ == null) {
          ensureSecondaryIdsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, secondaryIds_);
          onChanged();
        } else {
          secondaryIdsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder clearSecondaryIds() {
        if (secondaryIdsBuilder_ == null) {
          secondaryIds_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          secondaryIdsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public Builder removeSecondaryIds(int index) {
        if (secondaryIdsBuilder_ == null) {
          ensureSecondaryIdsIsMutable();
          secondaryIds_.remove(index);
          onChanged();
        } else {
          secondaryIdsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex.Builder getSecondaryIdsBuilder(
          int index) {
        return getSecondaryIdsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder getSecondaryIdsOrBuilder(
          int index) {
        if (secondaryIdsBuilder_ == null) {
          return secondaryIds_.get(index);  } else {
          return secondaryIdsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public java.util.List<? extends com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
           getSecondaryIdsOrBuilderList() {
        if (secondaryIdsBuilder_ != null) {
          return secondaryIdsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(secondaryIds_);
        }
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex.Builder addSecondaryIdsBuilder() {
        return getSecondaryIdsFieldBuilder().addBuilder(
            com.elarian.hera.proto.CommonModel.CustomerIndex.getDefaultInstance());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public com.elarian.hera.proto.CommonModel.CustomerIndex.Builder addSecondaryIdsBuilder(
          int index) {
        return getSecondaryIdsFieldBuilder().addBuilder(
            index, com.elarian.hera.proto.CommonModel.CustomerIndex.getDefaultInstance());
      }
      /**
       * <code>repeated .com.elarian.hera.proto.CustomerIndex secondary_ids = 3;</code>
       */
      public java.util.List<com.elarian.hera.proto.CommonModel.CustomerIndex.Builder> 
           getSecondaryIdsBuilderList() {
        return getSecondaryIdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.elarian.hera.proto.CommonModel.CustomerIndex, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder, com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder> 
          getSecondaryIdsFieldBuilder() {
        if (secondaryIdsBuilder_ == null) {
          secondaryIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.elarian.hera.proto.CommonModel.CustomerIndex, com.elarian.hera.proto.CommonModel.CustomerIndex.Builder, com.elarian.hera.proto.CommonModel.CustomerIndexOrBuilder>(
                  secondaryIds_,
                  ((bitField0_ & 0x00000004) != 0),
                  getParentForChildren(),
                  isClean());
          secondaryIds_ = null;
        }
        return secondaryIdsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.elarian.hera.proto.IdentityState)
    }

    // @@protoc_insertion_point(class_scope:com.elarian.hera.proto.IdentityState)
    private static final com.elarian.hera.proto.IdentityStateOuterClass.IdentityState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.elarian.hera.proto.IdentityStateOuterClass.IdentityState();
    }

    public static com.elarian.hera.proto.IdentityStateOuterClass.IdentityState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdentityState>
        PARSER = new com.google.protobuf.AbstractParser<IdentityState>() {
      @java.lang.Override
      public IdentityState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IdentityState(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IdentityState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdentityState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.elarian.hera.proto.IdentityStateOuterClass.IdentityState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elarian_hera_proto_IdentityState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elarian_hera_proto_IdentityState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_elarian_hera_proto_IdentityState_MetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_elarian_hera_proto_IdentityState_MetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024identity_state.proto\022\026com.elarian.hera" +
      ".proto\032\022common_model.proto\"\240\002\n\rIdentityS" +
      "tate\0223\n\004tags\030\001 \003(\0132%.com.elarian.hera.pr" +
      "oto.CustomerIndex\022E\n\010metadata\030\002 \003(\01323.co" +
      "m.elarian.hera.proto.IdentityState.Metad" +
      "ataEntry\022<\n\rsecondary_ids\030\003 \003(\0132%.com.el" +
      "arian.hera.proto.CustomerIndex\032U\n\rMetada" +
      "taEntry\022\013\n\003key\030\001 \001(\t\0223\n\005value\030\002 \001(\0132$.co" +
      "m.elarian.hera.proto.DataMapValue:\0028\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.elarian.hera.proto.CommonModel.getDescriptor(),
        });
    internal_static_com_elarian_hera_proto_IdentityState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_elarian_hera_proto_IdentityState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elarian_hera_proto_IdentityState_descriptor,
        new java.lang.String[] { "Tags", "Metadata", "SecondaryIds", });
    internal_static_com_elarian_hera_proto_IdentityState_MetadataEntry_descriptor =
      internal_static_com_elarian_hera_proto_IdentityState_descriptor.getNestedTypes().get(0);
    internal_static_com_elarian_hera_proto_IdentityState_MetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_elarian_hera_proto_IdentityState_MetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.elarian.hera.proto.CommonModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
